library(vegan)
library(permute)
library(lattice)
library(methods)
otu=read.table("/TJPROJ1/MICRO/yangfenglong/meta/NHT150088/16sall/lms_6report/lms_May/04.Diversity/CateComp/DCA/make_otu_table.txt",header=T)
otu=t(otu)
dca=decorana(otu)
otu.cca=cca(otu)
total.eigen=otu.cca$tot.chi
dca1.percent=round(dca$evals[1]/total.eigen*100,digits=2)
dca2.percent=round(dca$evals[2]/total.eigen*100,digits=2)
x.label=paste("DCA1 ( ",dca1.percent,"%"," )",sep="")
y.label=paste("DCA2 ( ",dca2.percent,"%"," )",sep="")
groups = read.table("/TJPROJ1/MICRO/yangfenglong/meta/NHT150088/16sall/lms_6report/lms_May/04.Diversity/group.list", head=F,colClasses=c("character","character"))
dca_scores=scores(dca,choices=c(1,2))
write.table(dca_scores,file="/TJPROJ1/MICRO/yangfenglong/meta/NHT150088/16sall/lms_6report/lms_May/04.Diversity/CateComp/DCA/dca_scores.txt")
library(ggplot2)
groups = read.table("/TJPROJ1/MICRO/yangfenglong/meta/NHT150088/16sall/lms_6report/lms_May/04.Diversity/group.list", head=F,colClasses=c("character","character"))
scores=data.frame(
  sample=groups[,1],
  DCA1=dca_scores[,1],
  DCA2=dca_scores[,2],
  Group=groups[,2])
write.table(scores,file="/TJPROJ1/MICRO/yangfenglong/meta/NHT150088/16sall/lms_6report/lms_May/04.Diversity/CateComp/DCA/plot_DCA.txt",sep="\t",quote=F)
#AL=scores[,c(2,3,4,5)]
#rownames(scores)=c("sample","DCA1","DCA2","Group")
#pdf(file="")
#plot(dca,dis="site",type="test",xlab=x.label,ylab=y.label)
#dev.off
#scores = read.table("/TJPROJ1/MICRO/yangfenglong/meta/NHT150088/16sall/lms_6report/lms_May/04.Diversity/CateComp/DCA/plot_DCA.txt",header=T)
DCA=ggplot(scores,aes(DCA1,DCA2))+ geom_point(aes(colour=factor(Group)),size=5)
DCA=DCA+theme(panel.grid.major=element_blank())
DCA=DCA+theme(panel.grid.minor=element_blank())
DCA=DCA+theme(panel.background=element_blank())
DCA=DCA+theme(panel.background=element_rect(size=0.5))
DCA=DCA+theme(axis.text.x=element_text(size=14,colour="black"))
DCA=DCA+theme(axis.text.y=element_text(size=14,colour="black"))
DCA=DCA+theme(axis.title.x=element_text(size=16,colour="black"))+ labs(title="DCA Plot") +xlab(x.label)+ylab(y.label)
DCA=DCA+theme(axis.title.y=element_text(size=16,colour="black"))
DCA=DCA+theme(legend.text=element_text(size=16,colour="black"))
DCA=DCA+theme(axis.ticks=element_line(colour="black"))
DCA=DCA+theme(legend.title=element_blank())
DCA=DCA+theme(legend.key=element_blank())
DCA=DCA+geom_vline(aes(x=0,y=0),linetype="dotted")
DCA=DCA+geom_hline(aes(x=0,y=0),linetype="dotted")
ggsave("/TJPROJ1/MICRO/yangfenglong/meta/NHT150088/16sall/lms_6report/lms_May/04.Diversity/CateComp/DCA/DCA.pdf",width=12,height=9)
ggsave("/TJPROJ1/MICRO/yangfenglong/meta/NHT150088/16sall/lms_6report/lms_May/04.Diversity/CateComp/DCA/DCA.svg",width=12,height=9)
